Resources:
  S3BucketRedirectToWWW:
    Type: AWS::S3::Bucket
    Condition: DomainIsWWW
    Properties:
      BucketName:
        !Join
        - '-'
        - - !Ref AWS::AccountId
          - ${env:DOMAIN}
          - redirect-to-www
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName:
            !Join
            - '.'
            - - 'www'
              - ${env:DOMAIN}
          Protocol: https
