image: weblablv/wl-bitbucket-sls-ci:latest

pipelines:
  branches:
    master:
      - step:
          name: Deploy
          script:
            - /opt/weblablv/deploy.sh
    dev:
      - step:
          name: Deploy
          script:
            - /opt/weblablv/deploy.sh
