service: ${ self:provider.parameters.aws.serviceId }

provider:
  name: aws
  runtime: nodejs12.x
  parameters: ${ file(config/index.js) }
  region: ${ opt:region, self:provider.parameters.aws.region }
  stage: ${ opt:stage, self:provider.parameters.aws.stage }

plugins:
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-sequelize-migrations

resources:
  - ${ file(src/resources/s3/RedirectToWWW.yml) }
  - ${ file(src/resources/cloudFront/RedirectToWWW.yml) }
  - ${ file(src/resources/cloudFront/website.yml) }
