service: ${env:SERVICE_ID}

useDotenv: true
configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_REGION}
  stage: prod

resources:
  - ${file(src/resources/cloudFront/website.yml)}
  - ${file(src/resources/cloudFront/redirectToWWW.yml)}
  - ${file(src/resources/s3/RedirectToWWW.yml)}
  - Conditions:
      DomainIsWWW: !Equals [ "${env:DOMAIN_TYPE}", "www" ]
