Resources:
  CloudFrontRedirectToWWW:
    Type: AWS::CloudFront::Distribution
    Condition: DomainIsWWW
    Properties:
      DistributionConfig:
        Aliases:
          - ${env:DOMAIN}
        Origins:
          - Id: S3Origin
            DomainName: !Select [ 2, !Split [ "/", !GetAtt S3BucketRedirectToWWW.WebsiteURL ] ]
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 0
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - HEAD
            - GET
          SmoothStreaming: false
          DefaultTTL: 0
          MaxTTL: 0
          Compress: true
        Comment: ''
        PriceClass: PriceClass_All
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn: ${env:SSL_ARN}
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016
