Resources:
  CloudFrontWebsite:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !If
            - DomainIsWWW
            - !Join
              - '.'
              - - 'www'
                - ${ self:provider.parameters.domain }
            - ${ self:provider.parameters.domain }
        Origins:
          - Id: EC2
            DomainName: ${ self:provider.parameters.EC2InstanceAddress }
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - HEAD
            - GET
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad #Managed-CachingDisabled
          Compress: true
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3 #Managed-AllViewer
          SmoothStreaming: false
          TargetOriginId: EC2
          ViewerProtocolPolicy: redirect-to-https
        Comment:
          !Join
          - ' '
          - - 'Points EC2 of'
            - ${ self:provider.parameters.domain }
        PriceClass: PriceClass_All
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn: ${ self:provider.parameters.sslCertificateARN }
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016
